language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  firefox: 46.0
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g bower gulp-cli@1
- bower install
- gulp lint
- gulp switch
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s default; fi
env:
  global:
  - secure: JXQACDLgoprzbPeo7MW+7rwwUFvee6b+sWsTICnujLeTJyqtOLYK5DBKr+dtejd35QNaEANBFg4BXieujrvh2zkq/jguhgWFbUB3p+ZitC8WVsHHSTHP3C7vm4mNNE3/5EnO/FozWeVT65dWc4NFZQ0SAKMZkfs3HDqp0JX4Dvg=
  - secure: vqpcGG4E9MWVLimtTBc5iUzoKMVWPnPocxkAw0nY0tmPNeYIeU7V9j77qnwuL+XShIy+2D+VnZRndPOZHp+5GmqzRiXel8B7r4vKK3kyKnhNoGcZ+kDIuXdH3iUvoL12S0+MGcy5L7v8XsorYIuy0Vp2PvInjJM6DODNWrgLOLQ=
